### ISSUE TITLE
Problem with Revised Equation

### ISSUE THREAD

**Issue by ercrema** [ercrema/CultureAllee#7]
The current equation compares the intrinsic growth rate between the two populations. The intrinsic growth rate is given by these lines of code: 

https://github.com/ercrema/CultureAllee/blob/56a663f39068f26528ff64ead65ba56653330c75/src/allee.R#L17-18

The problem is that before Rm and Rn were internally multiplied with m and n:
https://github.com/ercrema/CultureAllee/commit/d497e27505324734f8282d2bb065f8275394c994#L17-18

Now with the old version this guaranteed that Rm=0 when m=0, and Rn=0 when n=0. But with the current implementation this doesn't happen. So you might have a negative infinite growth rate. Try the following settings:

r.m= 0.4946667
r.n= 0.05
z = 0.03
An = 0.56
Am =0.1
Kn= 1.06
Km = 0.6
ini.m= 0.8615385
ini.n= 0
b=2

with all the competition coefficient set to 0.

**Comment by ercrema** [comment]
The simplest solution I can imagine is to re-calculate DELTA, taking into consideration Rm and Rn with the terms m and n included. This way we can use the older version of the equation. I can work this probably only after you have settled in Vancouver, but I thought it was worth mentioning to you in case you have spare time in the flight. Also this was found why executing the overlap experiment on Legion. Clearly that helps a lot in finding bugs so definitely worth pursuing.

**Comment by xrubio** [comment]
Ok I see the problem...I'll be able to work next week on this and I also have the flight so let's work on this.

**Comment by ercrema** [comment]
Yup no worries, I'm also overwhelmed by EUROEVOL stuff, at least till Thursday. I think it's just a matter of finding a similar value for Delta putting m and n in Rm and Rn. Shouldn't be that difficult. The problem is whether assuming this makes sense or not...
